output_dir = 'examples/simple_with_preprocessor/output'
preprocessed_dir = 'examples/preprocessor/output'

[samples]
    #As = ['sample_data/ERR329501_chr4.bam']
    #Bs = ['sample_data/GSM1553106_chr4.bam']
	A = ['sample_data/ERR329501.bam']
    B = ['sample_data/GSM1553106.bam']



# 2274600 - preproce
#  190276
# 3752... something wrong?

# 194480
#2330860
